
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Chngpwd extends javax.swing.JFrame {

    /**
     * Creates new form Chngpwd
     */
    
    SQL q = new SQL("jdbc:oracle:thin:@localhost:1521:XE","oracle.jdbc.OracleDriver", "system", "iiita");
    public Chngpwd() {
        initComponents();
    }
    
    public Chngpwd(UserType u){
        usr = u;
        initComponents();
        System.out.println(usr.type);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cnew1 = new javax.swing.JPasswordField();
        new1 = new javax.swing.JPasswordField();
        old = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Original_Password  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        cnew1.setBackground(new java.awt.Color(204, 255, 255));
        cnew1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(cnew1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 150, 30));

        new1.setBackground(new java.awt.Color(204, 255, 255));
        new1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(new1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 150, 30));

        old.setBackground(new java.awt.Color(204, 255, 255));
        old.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(old, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 113, 150, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("New_Password  :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 70, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Confirm New_Password  :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(224, 247, 255));
        jLabel1.setText("CHANGE_PASSWORD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/green_abstract_background-wide_e0.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 355));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(usr.type.equals("ADMINISTRATOR")){
            String query = "select * from ADM_USER";
            q.executeQuery(query);
        try {
            while(q.rs.next()){
                String oldpwd = q.rs.getString("Password");
                if(old.getPassword().equals(oldpwd)){
                    String newpwd = new String(new1.getPassword());
                    if(newpwd.equals(cnew1.getPassword())){
                        
                            query = "UPDATE ADM_USER set password ='"+newpwd+"' where username = '"+usr.username+"'";
                            q.executeQuery(query);
                            JOptionPane.showMessageDialog(this, "Password changed Successfully !");
                            this.setVisible(false);
                    } else {
                            JOptionPane.showMessageDialog(this, "Something went wrong!!!");
                        }
                }
            }
             q.rs.close();
             q.conn.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this,e);
        }
    } else if(usr.type.equals("MANAGER")){
            String query = "select * from MAN_USER";
            q.executeQuery(query);
        try {
            while(q.rs.next()){
                String oldpwd = q.rs.getString("Password");
                System.out.println(oldpwd);
                if(old.getText().equals(oldpwd)){
                    System.out.println("Old Password == "+oldpwd);
                    String newpwd = new1.getText();
                    if(newpwd.equals(cnew1.getText())){
                        
                            query = "UPDATE MAN_USER set password ='" +newpwd+"' where username = '"+usr.username+"'";
                            q.executeQuery(query);
                            //q.rs.next();
                            JOptionPane.showMessageDialog(this, "Password changed Successfully !");
                             this.setVisible(false);
                    } else {
                            JOptionPane.showMessageDialog(this, "Something went wrong!!!");
                        }
                }
            } 
             q.rs.close();
            q.conn.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this,e);
        }
    } else if(usr.type.equals("EMPLOYEE")){
            String query = "select * from EMP_USER";
            q.executeQuery(query);
        try {
            while(q.rs.next()){
                String oldpwd = q.rs.getString("Password");
                if(old.getText().equals(oldpwd)){
                    System.out.println("Old Password == "+oldpwd);
                    String newpwd = new1.getText();
                    if(newpwd.equals(cnew1.getText())){
                        
                            query = "UPDATE EMP_USER set password ='" +newpwd+"' where username = '"+usr.username+"'";
                            q.executeQuery(query);
                            JOptionPane.showMessageDialog(this, "Password changed Successfully !");
                             this.setVisible(false);
                    } else {
                            JOptionPane.showMessageDialog(this, "Something went wrong!!!");
                        }
                }
            }
            q.rs.close();
            q.conn.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this,e);
        }
    } else if(usr.type == null) {
         this.setVisible(false);
    }
            try {
                q.rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(Chngpwd.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                q.conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(Chngpwd.class.getName()).log(Level.SEVERE, null, ex);
            }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chngpwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chngpwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chngpwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chngpwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chngpwd().setVisible(true);
            }
        });
    }
    private UserType usr;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cnew1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField new1;
    private javax.swing.JPasswordField old;
    // End of variables declaration//GEN-END:variables
}
